version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: cakephp_app
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    command: >
      bash -c "apt-get update && apt-get install -y zip unzip libicu-dev libxml2-dev libonig-dev git &&
               docker-php-ext-install intl pdo pdo_mysql mbstring &&
               apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revex
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
